apiVersion: v1
kind: Pod
metadata:
  name: custom-nginx-pod
  labels:
    app: webserver
spec:
  containers:
  - name: custom-nginx-container
    image: kavitadalvi/custom_nginx:latest
    ports:
    - containerPort: 80
